config/routes.rb
Rails.application.routes.draw do

  root 'estados#index'

  get 'votar' => 'estados#votar'
	get 'resultados' => 'estados#resultados'
  get 'reset' => 'estados#reset'
	get 'login' => 'login#form'
	get 'logout' => 'login#logout'
	get 'sesion' => 'login#login'

end

app/models/estado.rb
class Estado < ActiveRecord::Base

  def self.contar_votos
    Hash[ Estado.all.map{ |e| [e.nombre, e.votos] } ]
  end	

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base

  def self.authenticate(username, password)
		usuario = self.where(:username => username).first
		if usuario
			given_passwd = Usuario.encrypt_password(password)
			if usuario.password != given_passwd
				usuario = nil
			end
		end
		return usuario
	end

	private

		def self.encrypt_password(password)
			string = password + "1t3sM"
			Digest::SHA1.hexdigest(string)
		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	def require_session
    @user = Usuario.find session[:user_id] if session[:user_id]
    if @user.nil?
      redirect_to login_url, alert: "Por favor inicia sesión"  
    end
  end

end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
	before_action :require_session, only: [:resultados, :reset]
  
	def index
    @estados = Estado.all
  end

	def votar
		if params[:estado]
			estado = Estado.find(params[:estado][:estado_id])
			estado.votos += 1
			estado.save
			redirect_to root_url, notice: '¡Gracias por tu voto!'
		else
			redirect_to root_url, alert: 'Debes seleccionar un estado de ánimo.'
		end
	end

  def resultados
    @votos = Estado.contar_votos
  end

	def reset
		Estado.update_all(votos: 0)
    redirect_to root_url, notice: 'El contador de votos se ha reiniciado'
	end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
	def form
	end

	def login
		@user = Usuario.authenticate(params[:username], params[:password])
    if @user.nil?
      redirect_to root_url, alert: 'Usuario/contraseña no válido'
    else
      session[:user_id] = @user.id
     	redirect_to root_url, notice: 'Login exitoso'
    end
	end

	def logout
    reset_session
    redirect_to root_url, notice: "Has cerrado sesión"      
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/estados/index.html.erb
<script>
	$("#votar").addClass("active");
</script>

<div class="page-header">
  <h2>Termómetro <small>Elige tu estado de ánimo</small></h2>
</div>

<%= form_tag('/votar', method: 'get', class: 'form-horizontal') do %>
	<div class="row">
	<div class="col-md-8 col-md-offset-2">
  	<%= collection_radio_buttons(:estado, :estado_id, Estado.all, :id, :nombre) do |b| %>
			<div class="col-md-3">
				<label class="radio text-center">
					<%= image_tag(b.text.downcase + ".png") %>
					<h4>
						<%= b.radio_button %>
			    	<%= b.text %>
					</h4>
					<br>
				</label>
			</div>
		<% end %>
		<div class="col-md-6 col-md-offset-3">
			<%= submit_tag('Votar', class: 'btn btn-primary btn-lg btn-block') %>
		</div>
	</div>
	</div>
<% end %>

app/views/estados/resultados.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<script>
	$("#resultados").addClass("active");
</script>

<div class="page-header">
  <h2>Resultados</h2>
</div>

<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<%= pie_chart @votos %>
	</div>
</div>

<div class="row">
	<div class="col-md-1 col-md-offset-11">
		<%= link_to 'Reset', reset_path, data: { confirm: '¿Estás seguro?' }, class: 'btn btn-danger' %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Termometro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if notice %>
		<p class="alert alert-success"><span class="close" data-dismiss="alert">&times;</span><%= notice %></p>
	<% end %>
	<% if alert %>
		<p class="alert alert-danger"><span class="close" data-dismiss="alert">&times;</span><%= alert %></p>
	<% end %>

	<ul class="nav nav-tabs">
    <li role="presentation" id="votar"><%= link_to 'Votar', root_path %></li>
		<% if session[:user_id] %>
    	<li role="presentation" id="resultados"><%= link_to 'Resultados', resultados_path, method: :get %></li>
			<li role="presentation" id="logout"><%= link_to 'Logout', logout_path, method: :get %></li>
		<% else %>
			<li role="presentation" id="login"><%= link_to 'Login', login_path %></li>
		<% end %>
  </ul>

  <div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/login/form.html.erb
<script>
	$("#login").addClass("active");
</script>

<div class="row"><br><br><br></div>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Inicia sesión</h3>
			</div>
			<div class="panel-body">
				<%= form_tag('/sesion', method: 'get', class: 'form-horizontal') do %>
					<div class="input-group input-group-lg">
						<span class="input-group-addon" id="sizing-addon1">@</span>
						<input type="text" name="username" class="form-control" placeholder="Usuario" aria-describedby="sizing-addon1">
					</div><br>

					<div class="input-group input-group-lg">
						<span class="input-group-addon" id="sizing-addon2">@</span>
						<input type="password" name="password" class="form-control" placeholder="Contraseña" aria-describedby="sizing-addon2">
					</div><br>
										
					<%= submit_tag('Login', class: 'btn btn-success btn-lg btn-block') %>
				<% end %>
			</div>
		</div>
	</div>
<div>